const sampleProperties = [
  {
    _id: '1',
    name: 'Modern Apartment',
    location: 'Downtown',
    price: 120000,
    description: 'A beautiful modern apartment in the heart of the city.',
    image: '/src/assets/images/1.jpg',
  },
  {
    _id: '2',
    name: 'Cozy Cottage',
    location: 'Suburbia',
    price: 80000,
    description: 'A cozy cottage with a charming garden.',
    image: '/src/assets/images/2.jpg',
  },
  {
    _id: '3',
    name: 'Luxury Villa',
    location: 'Countryside',
    price: 250000,
    description: 'A luxurious villa with stunning views.',
    image: '/src/assets/images/3.jpg',
  },
  {
    _id: '4',
    name: 'Beachfront Bungalow',
    location: 'Coastal Area',
    price: 180000,
    description: 'A cozy bungalow right by the beach.',
    image: '/src/assets/images/4.jpg',
  },
  {
    _id: '5',
    name: 'Mountain Retreat',
    location: 'Mountain Range',
    price: 160000,
    description: 'A peaceful retreat nestled in the mountains.',
    image: '/src/assets/images/5.jpg',
  },
  {
    _id: '6',
    name: 'City Penthouse',
    location: 'City Center',
    price: 350000,
    description: 'An exclusive penthouse with panoramic city views.',
    image: '/src/assets/images/6.jpg',
  },
  {
    _id: '7',
    name: 'Riverside Mansion',
    location: 'Riverbank',
    price: 500000,
    description: 'A grand mansion overlooking a serene river.',
    image: '/src/assets/images/7.jpg',
  },
  {
    _id: '8',
    name: 'Historic Castle',
    location: 'Old Town',
    price: 1000000,
    description: 'A historic castle with medieval charm.',
    image: '/src/assets/images/8.jpg',
  },
  {
    _id: '9',
    name: 'Eco-Friendly House',
    location: 'Green Suburb',
    price: 200000,
    description: 'A sustainable house with modern eco-friendly features.',
    image: '/src/assets/images/9.jpg',
  },
  {
    _id: '10',
    name: 'Ski Chalet',
    location: 'Ski Resort',
    price: 300000,
    description: 'A cozy chalet perfect for winter sports enthusiasts.',
    image: '/src/assets/images/10.jpg',
  },
  {
    _id: '11',
    name: 'Desert Oasis',
    location: 'Desert',
    price: 220000,
    description: 'An oasis retreat in the midst of the desert.',
    image: '/src/assets/images/11.jpg',
  }
];

export default sampleProperties;
